### ISSUE TITLE
reduce API calls

### ISSUE THREAD

**Issue by smierz** [eschares/OpenAlex-CitedReferences#1]
Hi @eschares ,
I stumbled across your notebook and saw the comments at the end about the time complexity and wanted to offer some advice:

* there is a new [notebook about paging](https://github.com/ourresearch/openalex-api-tutorials/blob/main/notebooks/getting-started/paging.ipynb) that might be of interest for your main loop

* In your loop you call the API once for each referenced work, but you might want to switch to using another URL instead
  * you could use the [cited_by](https://docs.openalex.org/api/get-lists-of-entities/filter-entity-lists#cited_by) filter with each OpenAlex ID
  * an even better approach would be to set 'per_page' to 50 in the outer loop (looping through list of results of 'filtered_works_url') and then extract the OpenAlex ID for all 50 results per page and concat them using the [logical operator "OR"](https://docs.openalex.org/api/get-lists-of-entities/filter-entity-lists#addition-or) to use them as value for 'cited_by'. Though the notebook is unfinished yet, you can see this approach here (step 2) https://github.com/ourresearch/openalex-api-tutorials/blob/add-venues-jif/notebooks/venues/journal-impact-factor.ipynb

* I don't know, if you are planning other analysis with the data, but if you are only interested in the distribution of publication years, you might want to use 'group_by=publication_year' with your URL and sum up the values for each API call in a dictionary

* you might want to use a 'session' (part of python package 'requests') for doing multiple calls to the same API, this will reuse the connection

Hope this helps to bring down the API calls / time!

**Comment by eschares** [comment]
Hi @smierz,
Thanks for your thoughtful comments; I'm glad you "stumbled across" this!

- I think you are absolutely right about the `cited_by` filter. I didn't know about that, and it looks like it's already doing what I take many more loops and calls to accomplish. I do worry about the number of references per article though. In the documentation example, there are 20 outgoing references, and `per_page` is 25, so they are all returned. In my early results, I have papers with up to 200 references. This would introduce another pagination or cursor loop. Alternatively, I could try to sort the papers by number of references, set `per_page` to 200 and combine as many as I could in one call, etc. But keeping track of that seems messy. I wll think about this some more...
- logical OR seems doable, but I do want to keep things structured - which paper made the reference, to what paper is it going, etc. If I combine multiple 'parent' papers into one call, I'll mix up all the references.
- Yes, I am planning to do more analysis than just year. I want to include journal title, field, # times the reference was cited, and more
- I didn't know about 'session', I will look at that more too.

Thanks very much for your ideas and comments!

**Comment by smierz** [comment]
Hi @eschares ,

1) yes, you would need two loops. If you switch from basic to cursor paging, it will clean up some of your variables.

2) logical OR: ideally you would store the information about works in one table (or in your case dataframe)  and the references in another table. To get works and their references you simply JOIN (merge) them.

If you are interested, I could outline the approach and do some coding, just let me know :)

**Comment by eschares** [comment]
@smierz - sure, that would be great! Thanks.
